-- V1__create_event_message_and_event_trigger_table.sql

CREATE TABLE IF NOT EXISTS t_coupon
(
    c_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_coupon_id    uuid         not null unique,
    c_code         varchar(255) not null unique,
    c_created_at   DATE         not null,
    c_max_usage    INT          not null,
    c_actual_usage INT          not null default 0,
    c_country      varchar(10)  not null,
    c_version      bigint       not null
);

CREATE TABLE IF NOT EXISTS t_coupon_user
(
    cu_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cu_user_id     VARCHAR(255) not null,
    cu_coupon_code VARCHAR(255) not null,
    cu_used_at     TIMESTAMP    not null
);

CREATE INDEX idx_coupon_code_user_id ON t_coupon_user (cu_coupon_code, cu_user_id);

CREATE INDEX idx_coupon_code ON t_coupon (c_code);